#!/usr/bin/env sh
case "$1" in
    draw)
		cat <<-EOF | paste -sd '' > "$UEBERZUG_FIFO"
		{ 
			"action": "add",
			"identifier": "$UEBERZUG_ID", 
			"path": "$2", 
			"width": $3, 
			"height": $4, 
			"x": $5, 
			"y": $6
		} 
		EOF
	;;
	*)
		cat <<-EOF | paste -sd '' > "$UEBERZUG_FIFO"
		{
			"action": "remove",
			"identifier": "$UEBERZUG_ID"
		}
		EOF
;;
esac
