#!/usr/bin/env sh
{
draw() {
	# stolen from voidrice/lf/scope
		printf '{"action": "add", "identifier": "%s", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$UEBERZUG_ID" "$4" "$5" "$(($2-1))" "$(($3-1))" "$1" > "$UEBERZUG_FIFO"
}

file="$1"; shift
case "$(file --dereference --brief --mime-type -- "$file")" in
	image/svg+xml) convert "$file" "$TMPTHUMBNAIL.png" && draw "$TMPTHUMBNAIL.png" "$@" ;;
	image/*) draw "$file" "$@" ;;
	audio/*) exiftool "$file" ;;
	video) ffmpeg -y -i "$file" -vframes 1 "$TMPTHUMBNAIL.png" && draw "$TMPTHUMBNAIL.png" "$@" ;;
	application/x-tar) tar tf "$file" ;;
	application/zip) unzip -l "$file" ;;
	application/x-iso9660-image) iso-info --no-header -l "$file" ;;
	application/x-7z-compressed) 7z l "$1" ;;
	application/pgp-encrypted) gpg -d -- "$1" ;;
	application/x-bittorrent) transmission-show "$1" ;;
	application/x-object) nm "$1";;
	application/pdf)  pdftoppm -png -f 1 -singlefile "$file" "$TMPTHUMBNAIL" && draw "$TMPTHUMBNAIL.png" "$@" ;;
	text/troff) man "$file" | col -b ;;
	*opendocument*) odt2txt "$1" ;;
#	text/html) w3m -dump "$1";;
	*) bat -pf --theme ansi "$file" ;;
esac

} 2>&1
exit 1
