#!/usr/bin/env sh
file="$1"; shift
{
	case "$file" in
		*.bmp|*.jpg|*.jpeg|*.png|*.xpm|*.webp|*.gif|*.jfif) ~/.config/lf/hl draw "$file" "$@" ;;
		*.wav|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus|*.as[fx]|*.mka|*.exe) exiftool "$file" ;;
		*.tar*|*.tgz) tar tf "$file" ;;
		*.zip|*.apk|*.jar|*.war|*.ear|*.oxt) unzip -l "$file" ;;
		*.iso) iso-info --no-header -l "$file" ;;
		*.7z) 7z l "$1" ;;
		*.[1-8]) man "$1" | col -b ;;
		*.torrent) transmission-show "$1" ;;
		*.odt|*.ods|*.odp|*.sxw) odt2txt "$1" ;;
		*.o) nm "$1";;
		*.doc) catdoc "$1" ;;
		*.docx) docx2txt "$1" - ;;
		*.xml|*.html) w3m -dump "$1";;
		*.xls|*.xlsx) ssconvert --export-type=Gnumeric_stf:stf_csv "$1" "fd://1" | bat -pf --theme ansi -l sv ;;
		*.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx)
			ffmpeg -y -i "$file" -vframes 1 "$TMPTHUMBNAIL.png" && ~/.config/lf/hl draw "$TMPTHUMBNAIL.png" "$@"
		;;
		*.pdf) pdftoppm -png -f 1 -singlefile "$file" "$TMPTHUMBNAIL" && ~/.config/lf/hl draw "$TMPTHUMBNAIL.png" "$@" ;;
		*.svg) convert "$1" "$TMPTHUMBNAIL.png" && ~/.config/lf/hl draw "$TMPTHUMBNAIL.png" "$@" ;;
		*) bat -pf --theme ansi "$file" ;;
	esac
} 2>&1
exit 127
