#!/usr/bin/env -S bash -x
for file in "$@"; do
	stat=$(stat -c '%y' "$file")
	stat=${stat:0:-10}
	stat=${stat//./_}
	stat=${stat/\ /_}
	stat=${stat//:/-}
	format=${file#*.}
	mv -nv "$file" $stat.$format
done
