#!/usr/bin/env -S sh -ex
eval "$(qmk config | sed 's/\.//')"
keymapfolder=${userqmk_home}/keyboards/${userkeyboard%/*}/keymaps/${userkeymap}
keyboardfolder=${userqmk_home}/keyboards/${userkeyboard}

case $1 in
	e) $EDITOR $keymapfolder/keymap.c ;;
	s) echo $keyboardfolder ;;
	j) mv -v $keymapfolder/keymap.c $keymapfolder/keymap.c.bak
		qmk json2c $2 -o $keymapfolder/keymap.c ;;
	f)
		kbmcu=atmega32u4
#		kbfw=$2
		kbfw="$(qmk compile -c | awk '/Checking/ { print $5 }')"
		printf 'searching for %s' $kbmcu
		while sleep 0.1; do
			( lsusb | grep atmega32u4 2>&1 >/dev/null) && break || printf '.'
		done && echo
		for act in "erase --force" "flash $userqmk_home/$kbfw" reset; do doas dfu-programmer $kbmcu $act; done ;;
esac
