#!/usr/bin/env sh
# shellcheck disable=2086
case $1 in
	norm) flameshot gui ;;
	fast) flameshot gui -s -c ;;
	win)
		win=$(xdotool getactivewindow)
		eval "$(xdotool getwindowgeometry --shell "$win")"
		flameshot gui --region ${WIDTH}x${HEIGHT}+${X}+${Y}
	;;
	list) printf '%s\n%s\n%s' norm fast win ;;
	*) echo "usage: ${0##*/} [norm] [fast] [win]" ;;
esac
