#!/usr/bin/env sh
# shellcheck disable=2086
# shellcheck disable=2059

funcparse() {
	funcs="norm fast main win"
	for func in $funcs; do printf "$1" "$func"; done
}
case $1 in

	norm) flameshot gui ;;
	fast) flameshot gui -s -c ;;
	main) flameshot screen --number 1 -c ;;
	win)
		win="$(xdotool getactivewindow)"
		eval "$(xdotool getwindowgeometry --shell "$win")"
		flameshot gui --region ${WIDTH}x${HEIGHT}+${X}+${Y}
	;;

	list) funcparse '%s\n' ;;
	*) 
		printf '%s' "usage: ${0##*/}"
		funcparse ' [%s]' && printf '\n'
	;;

esac
