#!/usr/bin/env bash

#{ 
#	IFS=:; while read -r n p; do
#	case $n in
#		[0-9]*) echo $n $p ;;
##		*[0-9]) echo $n ;;
#	esac
#	done < last
#} | sort | uniq

for a in {a..z}; do
	for b in {a..z}; do
		echo ${a}${b}eppy
	done
	echo ${a}eppy
done
