#!/usr/bin/env -S bash -x
userid=31ainet5mbryzxzo2f6h5fyu7hsq

# helpers
hand() {
	local oauth=BQBpOPXRrVv-IgnCH96GaZcRUiJYW5AhCxD87N_0UfdX6-K06WV5DG68QRT4yPOxuc1QKmEWv-KFzO6_xAiyMXTtW-jwV4LCxiac-y6aoI6N2Oir086CH8fZ7zKt_sAE3rCeMFV2kQfvD3ZpYMRS3NabUKegVt9DbqSzkm7M-53H0dMK4ZbNjSXCJHcZcVK8IbEQlAm2BpzKDo_2WOMMsNwLZyfZKj8CoDvqatOdJz86zDKMCw1wv_KcIVIc9WOUhUigxUNKitO1oMgtRd7CZshCH3vIcq392q6pvZWFr--SELr1
	curl -X "$1" "https://api.spotify.com/v1/$2" "${@:3}" -H "Authorization: Bearer $oauth"
}

delete() {
	while :; do
		read -r line < ~/.line
		playlistid=$(sed "${line}q;d" PLAYLISTS)
		local playlistid=${playlistid%%\ *}
	    hand DELETE "playlists/${playlistid}/followers"
		echo $(( line + 1 )) > ~/.line
	done
}

#check() {
#	while read -r n q; do
#		[[ $n = $num ]] && echo "$n cool" || { echo "$n ugly" && exit }
#		(( num++ ))
#	done <<< $(tac file)
#}

create() {
	while :; do
		read -r sum < ~/.sum
		data='{"name":"My Playlist #'$(printf "%'.0f\n" "$sum")'","public":true}'
		create="$(hand POST "users/$userid/playlists" --data "$data")"
		[[ "$create" == *"402"* ]] && exit
		[[ "$create" == *"400"* ]] && exit
		id="$(jq -r '.id' <<< "$create")"
		local track=1lvs1UC4nE3F8ZizzGUGYX
		hand POST "playlists/$id/tracks?uris=spotify%3Atrack%3A$track"
		echo $(( sum + 1 )) > ~/.sum
	done
}

get() {
	while :; do
		read -r offset < ~/.offset
		query=$(hand GET "users/$userid/playlists?limit=50&offset=$offset")
		jq -r '.items[]| .id + " " + .name' <<< "$query" >> PLAYLISTS
		echo $(( offset + 50 )) > ~/.offset
	done
}

# renamer cuz my brain cell jack fell off while making the creatah
##renamer() {
##	while :; do
##		playlistinfo="$(curl -s -X "GET" "https://api.spotify.com/v1/me/playlists?limit=1&offset=$sum" $curlargs -H "Authorization: Bearer $oauth")"
##		playlistname=$(jq -r '.items[].name' <<< $playlistinfo)
##		playlistid=$(jq -r '.items[].id' <<< $playlistinfo)
##		oldplaylistnumber="${playlistname:13}"
##		newplaylistnumber=$(printf "%'.0f\n" $oldplaylistnumber)
##		data="{\"name\":\"My Playlist #$newplaylistnumber\",\"public\":true}"
##		curl -X "PUT" "https://api.spotify.com/v1/playlists/$playlistid" --data "{\"name\":\"My Playlist #$newplaylistnumber\",\"public\":true}" $curlargs -H "Authorization: Bearer $oauth" 
##		sum=$(( sum + 1 ))
##	done	
##}

$1
