#!/usr/bin/env bash
set -x
[ $PLAYER_EVENT = load ] || exit 0
ID=2718

# metadata
dunstify -r $ID "${0##*/}" "getting info..."
player="$(playerctl -l | grep -E 'spotify|ncspot'| tail -1)"
info="$(playerctl metadata -p $player 2>&1)"
[[ $info = *"No"* ]] && dunstify -t 2000 -r $ID "${0##*/}" "spotifyd shat itself" && exit 0
dunstify -r $ID "${0##*/}" "formatting info..."
cutval="36-"
artist=$(grep -w artist <<< $info | cut -c $cutval)
artist=${artist//$'\n'/, }
artUrl=$(grep -w artUrl <<< $info | cut -c $cutval)
title=$(grep -w title <<< $info | cut -c $cutval)
album=$(grep -w album <<< $info | cut -c $cutval)

dunstify -r $ID "${0##*/}" "creating temp..."
temp="$(mktemp --suffix=$progname)"
dunstify -r $ID "${0##*/}" "downloading artUrl..."
curl $artUrl -o $temp
dunstify -r $ID -a Spotify -I $temp "$title" "$artist - $album"
rm -r $temp
