#!/usr/bin/env sh
# sv log wrapper (socklog), mainly for syntax highlighting

page() {
	bat -fPpl log --theme ansi "$@"
}

echo "waiting for bat to finish processing..."
page /var/log/socklog/*/current | sort -u
tail -Fq -n0 /var/log/socklog/*/current | page | uniq
