#!/usr/bin/env -S bash -ex
pkg=xbps-0.59.1_6.x86_64.xbps
while read -r syntax mirror _ loc; do
	case $syntax in
		\|)
			case $mirror in
				Repository) ;;
				*)
					mirror=${mirror#<}
					mirror=${mirror%>}
					loc=${loc% |}
					declare -A sum
					for i in {1..3}; do
						sum[$i]="$(curl -s --progress-bar -m 3 -w '%{speed_download}, %{time_connect}; %{time_total}' -o/dev/null "$mirror"/"$pkg")"
						declare tmp[$i]=${sum[$i]##*, }
						declare tim[$i]=${tmp[$i]##*. }
						declare con[$i]=${tmp[$i]%%;*}
						declare dl[$i]=${sum[$i]%%,*}
					done
					totalcon=$(calc -d "(${con[1]} + ${con[2]} + ${con[3]}) / 3" | tr -d '[:blank:]')
					totaldl=$(calc -d "(${dl[1]} + ${dl[2]} + ${dl[3]}) / 3" | tr -d '[:blank:]')
					totaltim=$(calc -d "(${tim[1]} + ${tim[2]} + ${tim[3]}) / 3" | tr -d '[:blank:]')
					printf "%-10s connected in %s, total %s, server %s based in %s\n" "${totaldl%.*}," "${totalcon:0:4}" "$totaltim" "$mirror" "$loc"
				;;
			esac
		;;
	esac
done <<< "$(curl https://raw.githubusercontent.com/void-linux/void-docs/master/src/xbps/repositories/mirrors/index.md)"
