#!/usr/bin/env bash
for to in main {,multilib{,/nonfree},nonfree}; do
	doas tee "/etc/xbps.d/${num:-00}-repository-${to//\//-}.conf" <<< "repository=${1:-https://repo-default.voidlinux.org}/current/${to#main}"
	num=10
done
