#!/usr/bin/env bash
color="$(sxcs -o --hex | cut -f 2)"
convert -size 256x256 xc:"$color" /tmp/color.png
xclip -sel c <<< "$color"
dunstify -r "$id" -I /tmp/color.png "$color" 'copied to clipboard'
rm /tmp/color.png
