#!/usr/bin/env -S bash -x

for i in $(seq 1 $1); do
	sleep 2
	eval "$(xdotool getmouselocation --shell)"
	XY[$i]="$X $Y"
done

sum=1
while :; do
	for i in "${XY[@]}"; do
		xdotool mousemove ${i%%\ *} ${i##*\ }
		case $sum in
			1) xdotool click 3 ;;
			2) xdotool click 1 ;;
			3) xdotool click 1 ;;
			4) sum=1 && xdotool click 3 ;;
		esac
		(( sum++ ))
		sleep 0.5
	done
done
